@startuml
class Produit {
  +id: int
  +nom: string
  +prix: Monnaie
  +quantiteEnStock: int
  +id_categorie: int
}
class Categorie {
  +id: int
  +nom: string
  +description: string
}
class Vente {
  +id: int
  +horodatage: datetime
  +total: Monnaie
  +id_caisse: int
  +statut: string
}
class LigneVente {
  +qte: int
}
class Caissier {
  +id: int
  +nom: string
}
class Caisse {
  +id: int
  +nom: string
  +statut: string
}
class ServiceProduit {
  +rechercher(critere, valeur): List[Produit]
}
class ServiceVente {
  +creer_vente(panier, id_caisse, id_caissier): Vente
  +retourner_vente(id_vente): boolean
}
class ServiceInventaire {
  +verifier_disponibilite(panier): List[string]
  +reserver_stock(panier)
  +restituer_stock(panier)
}
class ServicePaiement {
  +facturer(vente): boolean
}
class ServiceTransaction {
  +commencer()
  +valider()
  +annuler()
}

Produit "*" -- "1" Categorie
Produit "1" -- "0..*" LigneVente
LigneVente "*" -- "1" Vente
Caissier "1" -- "0..*" Vente
Caisse "1" -- "0..*" Vente
Caissier "1" -- "1" Caisse : utilise >
ServiceVente --> ServiceInventaire : utilise >
ServiceVente --> ServicePaiement : utilise >
ServiceVente --> ServiceTransaction : utilise >
Vente --> ServiceVente : utilise >
Vente --> ServiceProduit : utilise >
@enduml
